{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "File Management REST API",
    "description" : "File upload, list, delete and replace",
    "version" : "1.0.0-oas3"
  },
  "servers" : [ {
    "url" : "https://virtserver.swaggerhub.com/BORHAN96/file.management/1.0.0"
  } ],
  "paths" : {
    "/login" : {
      "post" : {
        "summary" : "Login",
        "description" : "Authenticate and get a token",
        "requestBody" : {
          "description" : "The username and password to authenticate",
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/login_body"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "401" : {
            "description" : "Access token is missing or invalid."
          },
          "200" : {
            "description" : "Successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_200"
                }
              }
            }
          }
        }
      }
    },
    "/files" : {
      "get" : {
        "summary" : "Get all files",
        "description" : "Get a list of all files",
        "responses" : {
          "401" : {
            "description" : "Access token is missing or invalid."
          },
          "200" : {
            "description" : "Successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/File"
                  }
                }
              }
            }
          }
        },
        "security" : [ {
          "bearerAuth" : [ ]
        } ]
      }
    },
    "/files/upload" : {
      "post" : {
        "summary" : "Upload a file",
        "description" : "Upload a new file to the database",
        "requestBody" : {
          "content" : {
            "multipart/form-data" : {
              "schema" : {
                "$ref" : "#/components/schemas/files_upload_body"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "401" : {
            "description" : "Access token is missing or invalid."
          },
          "200" : {
            "description" : "Uploaded the file successfully, fileName"
          },
          "415" : {
            "description" : "Unsupported file type"
          }
        },
        "security" : [ {
          "bearerAuth" : [ ]
        } ]
      }
    },
    "/files/{id}" : {
      "get" : {
        "summary" : "Get a file by ID",
        "description" : "Get a file by its ID",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "The ID of the file to get",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "401" : {
            "description" : "Access token is missing or invalid."
          },
          "200" : {
            "description" : "Successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/File"
                }
              }
            }
          },
          "404" : {
            "description" : "File not found"
          }
        },
        "security" : [ {
          "bearerAuth" : [ ]
        } ]
      },
      "put" : {
        "summary" : "Replace a file by ID",
        "description" : "Replace a file in the database with a new one by its ID",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "The ID of the file to replace",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "content" : {
            "multipart/form-data" : {
              "schema" : {
                "$ref" : "#/components/schemas/files_id_body"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "401" : {
            "description" : "Access token is missing or invalid."
          },
          "200" : {
            "description" : "Successful operation"
          },
          "404" : {
            "description" : "File not found"
          }
        },
        "security" : [ {
          "bearerAuth" : [ ]
        } ]
      },
      "delete" : {
        "summary" : "Delete a file by ID",
        "description" : "Delete a file from the database by its ID",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "The ID of the file to delete",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "401" : {
            "description" : "Access token is missing or invalid."
          },
          "200" : {
            "description" : "Successful operation"
          },
          "404" : {
            "description" : "File not found"
          }
        },
        "security" : [ {
          "bearerAuth" : [ ]
        } ]
      }
    },
    "/files/{id}/content" : {
      "get" : {
        "summary" : "Get a file content by ID",
        "description" : "Get a file content by its ID",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "The ID of the file to get",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "401" : {
            "description" : "Access token is missing or invalid."
          },
          "200" : {
            "description" : "Successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_200_1"
                }
              }
            }
          },
          "404" : {
            "description" : "File not found"
          }
        },
        "security" : [ {
          "bearerAuth" : [ ]
        } ]
      }
    }
  },
  "components" : {
    "schemas" : {
      "File" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer",
            "format" : "int64",
            "example" : 1
          },
          "fileName" : {
            "type" : "string",
            "example" : "pexels-kelvin-valerio-617278.jpg"
          },
          "fileSize" : {
            "type" : "integer",
            "format" : "int64",
            "example" : 2068006
          },
          "fileType" : {
            "type" : "string",
            "example" : "image/jpeg"
          },
          "filePath" : {
            "type" : "string",
            "example" : "http://localhost:8082/download/pexels-kelvin-valerio-617278.jpg"
          },
          "fileData" : {
            "type" : "string",
            "format" : "byte",
            "example" : "LzlqLzRBQVFTa1pKUmdBQkFRRUFTQUJJQUE0Z3hZU1VORFgxQlNUMFpKVEVVQUFRRUFBQXhJVEdsdWJ3SVFBQUJ0Ym5SeVVrZENJRmhaV2lBSHo="
          }
        }
      },
      "login_body" : {
        "required" : [ "password", "username" ],
        "type" : "object",
        "properties" : {
          "username" : {
            "type" : "string",
            "example" : "anakin"
          },
          "password" : {
            "type" : "string",
            "example" : "password"
          }
        }
      },
      "inline_response_200" : {
        "type" : "object",
        "properties" : {
          "token" : {
            "type" : "string",
            "description" : "The token to use for subsequent requests",
            "example" : "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmFraW4iLCJpYXQiOjE2Nzc2OTg5NjAsImV4cCI6MTY3NzczNDk2MH0"
          }
        }
      },
      "files_upload_body" : {
        "required" : [ "file" ],
        "type" : "object",
        "properties" : {
          "file" : {
            "type" : "string",
            "description" : "The file to upload",
            "format" : "binary"
          }
        }
      },
      "files_id_body" : {
        "required" : [ "file" ],
        "type" : "object",
        "properties" : {
          "file" : {
            "type" : "string",
            "format" : "binary"
          }
        }
      },
      "inline_response_200_1" : {
        "type" : "object",
        "properties" : {
          "fileData" : {
            "type" : "string",
            "format" : "byte",
            "example" : "LzlqLzRBQVFTa1pKUmdBQkFRRUFTQUJJQUE0Z3hZU1VORFgxQlNUMFpKVEVVQUFRRUFBQXhJVEdsdWJ3SVFBQUJ0Ym5SeVVrZENJRmhaV2lBSHo="
          }
        }
      }
    },
    "responses" : {
      "UnauthorizedError" : {
        "description" : "Access token is missing or invalid."
      }
    },
    "securitySchemes" : {
      "bearerAuth" : {
        "type" : "http",
        "scheme" : "bearer",
        "bearerFormat" : "JWT"
      }
    }
  }
}